apiVersion: apps/v1
kind: Deployment
metadata:
  name: babafr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: babafr
  template:
    metadata:
      labels:
        app: babafr
    spec:
      containers:
      - image: okteto.dev/babafr:latest
        name: babafr
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/Tuxedo-html.zip"
        - name: Vless_UUID
          value: "3f7be32e-8890-45f5-ac26-9107e76b6fa3"
        - name: Vless_Path
          value: "/3f7be32e-8890-45f5-ac26-9107e76b6fa3-vless"
        - name: Vmess_UUID
          value: "3f7be32e-8890-45f5-ac26-9107e76b6fa3"
        - name: Vmess_Path
          value: "/3f7be32e-8890-45f5-ac26-9107e76b6fa3-vmess"
        - name: Share_Path
          value: "/vnwk"
